# Generated by Django 2.1.15 on 2020-02-12 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gitpull', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sshauth',
            name='posting_date',
        ),
    ]
