# Generated by Django 2.1.15 on 2020-01-28 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=50)),
                ('hotel_id', models.CharField(default='', max_length=1)),
                ('site_fqdn', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
